//-----------------------------------------------------------------------------
// Copyright (C) Proxmark3 contributors. See AUTHORS.md for details.
//-----------------------------------------------------------------------------
#include "clocks.h"

// FPGA clocks are fixed/generated by bitstream, so we don't need to configure PLLs here.
void mck_from_pll_to_slck(void) {
    // No-op
}

void mck_from_slck_to_pll(void) {
    // No-op
}
